import { writeFile } from "node:fs/promises";
import { conceptIndexPath, libraryRelativePath } from "./layout.js";
import { listRecordFiles, readRecordMetadata } from "./managed-documents.js";
import type { EntityType, RelationshipType } from "./types.js";

export interface ConceptEntry {
  name: string;
  type: EntityType;
  description: string;
  documents: string[];
  relations: Array<{ type: RelationshipType; to: string }>;
}

export interface ConceptIndex {
  document_count: number;
  concept_count: number;
  concepts: ConceptEntry[];
}

const MAX_MARKDOWN_CONCEPTS = 300;
const MAX_DESCRIPTION_LENGTH = 160;

function conceptKey(type: string, name: string): string {
  return `${type}:${name.trim().toLowerCase()}`;
}

/** Aggregates the entities and relationships declared across all records into one concept list. */
export async function buildConceptIndex(
  projectRoot: string,
  input: { type?: string; query?: string } = {}
): Promise<ConceptIndex> {
  // Earliest documents win the display name and description of a shared concept, so output is stable.
  const records = (await listRecordFiles(projectRoot))
    .sort((a, b) => a.created_at.localeCompare(b.created_at) || a.file_path.localeCompare(b.file_path));
  const concepts = new Map<string, ConceptEntry>();
  for (const record of records) {
    const metadata = await readRecordMetadata(projectRoot, record.id);
    const byName = new Map<string, ConceptEntry>();
    for (const entity of metadata.entities) {
      const key = conceptKey(entity.type, entity.name);
      let entry = concepts.get(key);
      if (!entry) {
        entry = { name: entity.name.trim(), type: entity.type, description: entity.description.trim(), documents: [], relations: [] };
        concepts.set(key, entry);
      }
      if (!entry.documents.includes(record.file_path)) {
        entry.documents.push(record.file_path);
      }
      byName.set(entity.name.trim().toLowerCase(), entry);
    }
    for (const relationship of metadata.relationships) {
      const from = byName.get(relationship.from.trim().toLowerCase());
      if (from && !from.relations.some((value) => value.type === relationship.type && value.to === relationship.to.trim())) {
        from.relations.push({ type: relationship.type, to: relationship.to.trim() });
      }
    }
  }

  const query = input.query?.trim().toLowerCase();
  const list = [...concepts.values()]
    .filter((entry) => !input.type || entry.type === input.type)
    .filter((entry) => !query || entry.name.toLowerCase().includes(query) || entry.description.toLowerCase().includes(query))
    .map((entry) => ({ ...entry, documents: entry.documents.sort() }))
    .sort((a, b) => b.documents.length - a.documents.length || a.name.localeCompare(b.name));
  return { document_count: records.length, concept_count: list.length, concepts: list };
}

export function renderConceptIndex(index: ConceptIndex): string {
  const lines = [
    "# DocNexus concepts",
    "",
    "<!-- Generated by docnexus; do not edit. Regenerated after every memory change. -->",
    "",
    `Project memory holds ${index.document_count} document(s) and ${index.concept_count} concept(s).`,
    "When a task touches a concept below, run the `docnexus-recall` skill before acting.",
    ""
  ];
  if (index.concepts.length === 0) {
    lines.push("_No concepts yet. Capture project knowledge with the `docnexus` skill._", "");
    return `${lines.join("\n")}`;
  }
  const shown = index.concepts.slice(0, MAX_MARKDOWN_CONCEPTS);
  const types = [...new Set(shown.map((entry) => entry.type))].sort();
  for (const type of types) {
    lines.push(`## ${type}`, "");
    for (const entry of shown.filter((value) => value.type === type)) {
      const description = entry.description.length > MAX_DESCRIPTION_LENGTH
        ? `${entry.description.slice(0, MAX_DESCRIPTION_LENGTH - 1)}…`
        : entry.description;
      const relations = entry.relations.map((relation) => `${relation.type} ${relation.to}`).join("; ");
      const documents = entry.documents.map((path) => `\`${libraryRelativePath(path)}\``).join(", ");
      lines.push(`- **${entry.name}** — ${description}${relations ? ` (${relations})` : ""} → ${documents}`);
    }
    lines.push("");
  }
  if (index.concepts.length > shown.length) {
    lines.push(`_${index.concepts.length - shown.length} more concept(s); run \`docnexus concepts\` for the full list._`, "");
  }
  return lines.join("\n");
}

export async function writeConceptIndex(projectRoot: string): Promise<void> {
  await writeFile(conceptIndexPath(projectRoot), renderConceptIndex(await buildConceptIndex(projectRoot)));
}
